name: flutter_virwave
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.2.18
  flutter_login: ^4.2.0
  sign_in_button: ^3.2.0
  image: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/animal_map.jpg
    - assets/images/pop_up.jpg
    - assets/images/icons/virwave_logo.png
    - assets/images/icons/heart_0.png
    - assets/images/icons/heart_25.png
    - assets/images/icons/heart_50.png
    - assets/images/icons/heart_75.png
    - assets/images/icons/heart_100.png
    - assets/images/animals/animal/axolotl.png
    - assets/images/icons/sleep.png
    - assets/images/icons/smile.png
    - assets/images/animals/sleep/axolotl_sleep.png
    - assets/images/animals/eat/axolotl_eat.png
    - assets/images/animals/background/axolotl_bg.png
